Ignore .eggs folder while running coveralls coverage
Cloud-CV/evalai-cli pull request #289
Opened 2020-10-22 15:26 UTC by Ram81

### Description

Ignore `.eggs` folder from coverage check. See this [report](https://coveralls.io/builds/34361516) for reference.

2020-10-22 15:54 UTC, RishabhJain2018 requested changes
Can you please update the version of coverage here: https://github.com/Cloud-CV/evalai-cli/blob/master/setup.py#L30 and remove from the `.travis` file.

2020-10-22 15:58 UTC, Ram81 commented
But the travis step was overriding the coverage version right? It will start failing again

2020-10-22 16:01 UTC, RishabhJain2018 commented
Yes, I think it was due to this only. Let's try it and it should work. It doesn't look right to have two different versions for the same thing.

2020-10-23 18:29 UTC, RishabhJain2018 commented
@Ram81 It is failing again, I think we will need to revert to the original thing. Can you please do that.

2020-10-25 17:29 UTC, Ram81 commented
@RishabhJain2018 Please take a look.

2020-10-25 20:45 UTC, RishabhJain2018 approved these changes

2020-10-25 20:45 UTC, merged